/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dksou.fitting.datasource.service;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2019-06-21")
public class DKDBConf implements org.apache.thrift.TBase<DKDBConf, DKDBConf._Fields>, java.io.Serializable, Cloneable, Comparable<DKDBConf> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DKDBConf");

  private static final org.apache.thrift.protocol.TField QUEUE__NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("QUEUE_NAME", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PRINCIPAL_FIELD_DESC = new org.apache.thrift.protocol.TField("PRINCIPAL", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField KEYTAB_FIELD_DESC = new org.apache.thrift.protocol.TField("KEYTAB", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DKDBConfStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DKDBConfTupleSchemeFactory();

  public java.lang.String QUEUE_NAME; // optional
  public java.lang.String PRINCIPAL; // optional
  public java.lang.String KEYTAB; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    QUEUE__NAME((short)2, "QUEUE_NAME"),
    PRINCIPAL((short)3, "PRINCIPAL"),
    KEYTAB((short)4, "KEYTAB");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 2: // QUEUE__NAME
          return QUEUE__NAME;
        case 3: // PRINCIPAL
          return PRINCIPAL;
        case 4: // KEYTAB
          return KEYTAB;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.QUEUE__NAME,_Fields.PRINCIPAL,_Fields.KEYTAB};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.QUEUE__NAME, new org.apache.thrift.meta_data.FieldMetaData("QUEUE_NAME", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRINCIPAL, new org.apache.thrift.meta_data.FieldMetaData("PRINCIPAL", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.KEYTAB, new org.apache.thrift.meta_data.FieldMetaData("KEYTAB", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DKDBConf.class, metaDataMap);
  }

  public DKDBConf() {
    this.QUEUE_NAME = "default";

    this.PRINCIPAL = "";

    this.KEYTAB = "";

  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DKDBConf(DKDBConf other) {
    if (other.isSetQUEUE_NAME()) {
      this.QUEUE_NAME = other.QUEUE_NAME;
    }
    if (other.isSetPRINCIPAL()) {
      this.PRINCIPAL = other.PRINCIPAL;
    }
    if (other.isSetKEYTAB()) {
      this.KEYTAB = other.KEYTAB;
    }
  }

  public DKDBConf deepCopy() {
    return new DKDBConf(this);
  }

  @Override
  public void clear() {
    this.QUEUE_NAME = "default";

    this.PRINCIPAL = "";

    this.KEYTAB = "";

  }

  public java.lang.String getQUEUE_NAME() {
    return this.QUEUE_NAME;
  }

  public DKDBConf setQUEUE_NAME(java.lang.String QUEUE_NAME) {
    this.QUEUE_NAME = QUEUE_NAME;
    return this;
  }

  public void unsetQUEUE_NAME() {
    this.QUEUE_NAME = null;
  }

  /** Returns true if field QUEUE_NAME is set (has been assigned a value) and false otherwise */
  public boolean isSetQUEUE_NAME() {
    return this.QUEUE_NAME != null;
  }

  public void setQUEUE_NAMEIsSet(boolean value) {
    if (!value) {
      this.QUEUE_NAME = null;
    }
  }

  public java.lang.String getPRINCIPAL() {
    return this.PRINCIPAL;
  }

  public DKDBConf setPRINCIPAL(java.lang.String PRINCIPAL) {
    this.PRINCIPAL = PRINCIPAL;
    return this;
  }

  public void unsetPRINCIPAL() {
    this.PRINCIPAL = null;
  }

  /** Returns true if field PRINCIPAL is set (has been assigned a value) and false otherwise */
  public boolean isSetPRINCIPAL() {
    return this.PRINCIPAL != null;
  }

  public void setPRINCIPALIsSet(boolean value) {
    if (!value) {
      this.PRINCIPAL = null;
    }
  }

  public java.lang.String getKEYTAB() {
    return this.KEYTAB;
  }

  public DKDBConf setKEYTAB(java.lang.String KEYTAB) {
    this.KEYTAB = KEYTAB;
    return this;
  }

  public void unsetKEYTAB() {
    this.KEYTAB = null;
  }

  /** Returns true if field KEYTAB is set (has been assigned a value) and false otherwise */
  public boolean isSetKEYTAB() {
    return this.KEYTAB != null;
  }

  public void setKEYTABIsSet(boolean value) {
    if (!value) {
      this.KEYTAB = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case QUEUE__NAME:
      if (value == null) {
        unsetQUEUE_NAME();
      } else {
        setQUEUE_NAME((java.lang.String)value);
      }
      break;

    case PRINCIPAL:
      if (value == null) {
        unsetPRINCIPAL();
      } else {
        setPRINCIPAL((java.lang.String)value);
      }
      break;

    case KEYTAB:
      if (value == null) {
        unsetKEYTAB();
      } else {
        setKEYTAB((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case QUEUE__NAME:
      return getQUEUE_NAME();

    case PRINCIPAL:
      return getPRINCIPAL();

    case KEYTAB:
      return getKEYTAB();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case QUEUE__NAME:
      return isSetQUEUE_NAME();
    case PRINCIPAL:
      return isSetPRINCIPAL();
    case KEYTAB:
      return isSetKEYTAB();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof DKDBConf)
      return this.equals((DKDBConf)that);
    return false;
  }

  public boolean equals(DKDBConf that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_QUEUE_NAME = true && this.isSetQUEUE_NAME();
    boolean that_present_QUEUE_NAME = true && that.isSetQUEUE_NAME();
    if (this_present_QUEUE_NAME || that_present_QUEUE_NAME) {
      if (!(this_present_QUEUE_NAME && that_present_QUEUE_NAME))
        return false;
      if (!this.QUEUE_NAME.equals(that.QUEUE_NAME))
        return false;
    }

    boolean this_present_PRINCIPAL = true && this.isSetPRINCIPAL();
    boolean that_present_PRINCIPAL = true && that.isSetPRINCIPAL();
    if (this_present_PRINCIPAL || that_present_PRINCIPAL) {
      if (!(this_present_PRINCIPAL && that_present_PRINCIPAL))
        return false;
      if (!this.PRINCIPAL.equals(that.PRINCIPAL))
        return false;
    }

    boolean this_present_KEYTAB = true && this.isSetKEYTAB();
    boolean that_present_KEYTAB = true && that.isSetKEYTAB();
    if (this_present_KEYTAB || that_present_KEYTAB) {
      if (!(this_present_KEYTAB && that_present_KEYTAB))
        return false;
      if (!this.KEYTAB.equals(that.KEYTAB))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetQUEUE_NAME()) ? 131071 : 524287);
    if (isSetQUEUE_NAME())
      hashCode = hashCode * 8191 + QUEUE_NAME.hashCode();

    hashCode = hashCode * 8191 + ((isSetPRINCIPAL()) ? 131071 : 524287);
    if (isSetPRINCIPAL())
      hashCode = hashCode * 8191 + PRINCIPAL.hashCode();

    hashCode = hashCode * 8191 + ((isSetKEYTAB()) ? 131071 : 524287);
    if (isSetKEYTAB())
      hashCode = hashCode * 8191 + KEYTAB.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(DKDBConf other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetQUEUE_NAME()).compareTo(other.isSetQUEUE_NAME());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQUEUE_NAME()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.QUEUE_NAME, other.QUEUE_NAME);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPRINCIPAL()).compareTo(other.isSetPRINCIPAL());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPRINCIPAL()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.PRINCIPAL, other.PRINCIPAL);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetKEYTAB()).compareTo(other.isSetKEYTAB());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKEYTAB()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.KEYTAB, other.KEYTAB);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DKDBConf(");
    boolean first = true;

    if (isSetQUEUE_NAME()) {
      sb.append("QUEUE_NAME:");
      if (this.QUEUE_NAME == null) {
        sb.append("null");
      } else {
        sb.append(this.QUEUE_NAME);
      }
      first = false;
    }
    if (isSetPRINCIPAL()) {
      if (!first) sb.append(", ");
      sb.append("PRINCIPAL:");
      if (this.PRINCIPAL == null) {
        sb.append("null");
      } else {
        sb.append(this.PRINCIPAL);
      }
      first = false;
    }
    if (isSetKEYTAB()) {
      if (!first) sb.append(", ");
      sb.append("KEYTAB:");
      if (this.KEYTAB == null) {
        sb.append("null");
      } else {
        sb.append(this.KEYTAB);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DKDBConfStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DKDBConfStandardScheme getScheme() {
      return new DKDBConfStandardScheme();
    }
  }

  private static class DKDBConfStandardScheme extends org.apache.thrift.scheme.StandardScheme<DKDBConf> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DKDBConf struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 2: // QUEUE__NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.QUEUE_NAME = iprot.readString();
              struct.setQUEUE_NAMEIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PRINCIPAL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.PRINCIPAL = iprot.readString();
              struct.setPRINCIPALIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // KEYTAB
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.KEYTAB = iprot.readString();
              struct.setKEYTABIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DKDBConf struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.QUEUE_NAME != null) {
        if (struct.isSetQUEUE_NAME()) {
          oprot.writeFieldBegin(QUEUE__NAME_FIELD_DESC);
          oprot.writeString(struct.QUEUE_NAME);
          oprot.writeFieldEnd();
        }
      }
      if (struct.PRINCIPAL != null) {
        if (struct.isSetPRINCIPAL()) {
          oprot.writeFieldBegin(PRINCIPAL_FIELD_DESC);
          oprot.writeString(struct.PRINCIPAL);
          oprot.writeFieldEnd();
        }
      }
      if (struct.KEYTAB != null) {
        if (struct.isSetKEYTAB()) {
          oprot.writeFieldBegin(KEYTAB_FIELD_DESC);
          oprot.writeString(struct.KEYTAB);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DKDBConfTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DKDBConfTupleScheme getScheme() {
      return new DKDBConfTupleScheme();
    }
  }

  private static class DKDBConfTupleScheme extends org.apache.thrift.scheme.TupleScheme<DKDBConf> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DKDBConf struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetQUEUE_NAME()) {
        optionals.set(0);
      }
      if (struct.isSetPRINCIPAL()) {
        optionals.set(1);
      }
      if (struct.isSetKEYTAB()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetQUEUE_NAME()) {
        oprot.writeString(struct.QUEUE_NAME);
      }
      if (struct.isSetPRINCIPAL()) {
        oprot.writeString(struct.PRINCIPAL);
      }
      if (struct.isSetKEYTAB()) {
        oprot.writeString(struct.KEYTAB);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DKDBConf struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.QUEUE_NAME = iprot.readString();
        struct.setQUEUE_NAMEIsSet(true);
      }
      if (incoming.get(1)) {
        struct.PRINCIPAL = iprot.readString();
        struct.setPRINCIPALIsSet(true);
      }
      if (incoming.get(2)) {
        struct.KEYTAB = iprot.readString();
        struct.setKEYTABIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

