/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dksou.fitting.dataprocess.service;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-10-31")
public class SelectRecService {

  public interface Iface {

    /**
     * 调用此方法可以筛选出符合条件的记录条数。
     * @param spStr分隔符号;
     * @param fdSum：字段数量;
     * @param whereStr：比较条件  f1 >= 2 and (f2=3 or f3=4)，f1为第一个字段;
     * @param srcDirName：源目录名;
     * @param dstDirName输出目录名，输出目录如果存在将会覆盖;
     * @param hostIp：要连接hiveserver主机的ip地址;
     * @param hostPort：hiveserver的端口，默认10000;
     * @param hostName：要连接主机的用户名;
     * @param hostPassword：要连接主机的密码（要具备执行Hadoop的权限的用户）;
     * 
     * @param spStr
     * @param fdSum
     * @param whereStr
     * @param srcDirName
     * @param dstDirName
     * @param hostIp
     * @param hostPort
     * @param hostName
     * @param hostPassword
     */
    public void selectRec(java.lang.String spStr, int fdSum, java.lang.String whereStr, java.lang.String srcDirName, java.lang.String dstDirName, java.lang.String hostIp, java.lang.String hostPort, java.lang.String hostName, java.lang.String hostPassword) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void selectRec(java.lang.String spStr, int fdSum, java.lang.String whereStr, java.lang.String srcDirName, java.lang.String dstDirName, java.lang.String hostIp, java.lang.String hostPort, java.lang.String hostName, java.lang.String hostPassword, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public void selectRec(java.lang.String spStr, int fdSum, java.lang.String whereStr, java.lang.String srcDirName, java.lang.String dstDirName, java.lang.String hostIp, java.lang.String hostPort, java.lang.String hostName, java.lang.String hostPassword) throws org.apache.thrift.TException
    {
      send_selectRec(spStr, fdSum, whereStr, srcDirName, dstDirName, hostIp, hostPort, hostName, hostPassword);
      recv_selectRec();
    }

    public void send_selectRec(java.lang.String spStr, int fdSum, java.lang.String whereStr, java.lang.String srcDirName, java.lang.String dstDirName, java.lang.String hostIp, java.lang.String hostPort, java.lang.String hostName, java.lang.String hostPassword) throws org.apache.thrift.TException
    {
      selectRec_args args = new selectRec_args();
      args.setSpStr(spStr);
      args.setFdSum(fdSum);
      args.setWhereStr(whereStr);
      args.setSrcDirName(srcDirName);
      args.setDstDirName(dstDirName);
      args.setHostIp(hostIp);
      args.setHostPort(hostPort);
      args.setHostName(hostName);
      args.setHostPassword(hostPassword);
      sendBase("selectRec", args);
    }

    public void recv_selectRec() throws org.apache.thrift.TException
    {
      selectRec_result result = new selectRec_result();
      receiveBase(result, "selectRec");
      return;
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void selectRec(java.lang.String spStr, int fdSum, java.lang.String whereStr, java.lang.String srcDirName, java.lang.String dstDirName, java.lang.String hostIp, java.lang.String hostPort, java.lang.String hostName, java.lang.String hostPassword, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      selectRec_call method_call = new selectRec_call(spStr, fdSum, whereStr, srcDirName, dstDirName, hostIp, hostPort, hostName, hostPassword, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class selectRec_call extends org.apache.thrift.async.TAsyncMethodCall<Void> {
      private java.lang.String spStr;
      private int fdSum;
      private java.lang.String whereStr;
      private java.lang.String srcDirName;
      private java.lang.String dstDirName;
      private java.lang.String hostIp;
      private java.lang.String hostPort;
      private java.lang.String hostName;
      private java.lang.String hostPassword;
      public selectRec_call(java.lang.String spStr, int fdSum, java.lang.String whereStr, java.lang.String srcDirName, java.lang.String dstDirName, java.lang.String hostIp, java.lang.String hostPort, java.lang.String hostName, java.lang.String hostPassword, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.spStr = spStr;
        this.fdSum = fdSum;
        this.whereStr = whereStr;
        this.srcDirName = srcDirName;
        this.dstDirName = dstDirName;
        this.hostIp = hostIp;
        this.hostPort = hostPort;
        this.hostName = hostName;
        this.hostPassword = hostPassword;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("selectRec", org.apache.thrift.protocol.TMessageType.CALL, 0));
        selectRec_args args = new selectRec_args();
        args.setSpStr(spStr);
        args.setFdSum(fdSum);
        args.setWhereStr(whereStr);
        args.setSrcDirName(srcDirName);
        args.setDstDirName(dstDirName);
        args.setHostIp(hostIp);
        args.setHostPort(hostPort);
        args.setHostName(hostName);
        args.setHostPassword(hostPassword);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public Void getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return null;
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("selectRec", new selectRec());
      return processMap;
    }

    public static class selectRec<I extends Iface> extends org.apache.thrift.ProcessFunction<I, selectRec_args> {
      public selectRec() {
        super("selectRec");
      }

      public selectRec_args getEmptyArgsInstance() {
        return new selectRec_args();
      }

      protected boolean isOneway() {
        return false;
      }

      
      protected boolean handleRuntimeExceptions() {
        return false;
      }

      public selectRec_result getResult(I iface, selectRec_args args) throws org.apache.thrift.TException {
        selectRec_result result = new selectRec_result();
        iface.selectRec(args.spStr, args.fdSum, args.whereStr, args.srcDirName, args.dstDirName, args.hostIp, args.hostPort, args.hostName, args.hostPassword);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("selectRec", new selectRec());
      return processMap;
    }

    public static class selectRec<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, selectRec_args, Void> {
      public selectRec() {
        super("selectRec");
      }

      public selectRec_args getEmptyArgsInstance() {
        return new selectRec_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<Void> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<Void>() { 
          public void onComplete(Void o) {
            selectRec_result result = new selectRec_result();
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            selectRec_result result = new selectRec_result();
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, selectRec_args args, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException {
        iface.selectRec(args.spStr, args.fdSum, args.whereStr, args.srcDirName, args.dstDirName, args.hostIp, args.hostPort, args.hostName, args.hostPassword,resultHandler);
      }
    }

  }

  public static class selectRec_args implements org.apache.thrift.TBase<selectRec_args, selectRec_args._Fields>, java.io.Serializable, Cloneable, Comparable<selectRec_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("selectRec_args");

    private static final org.apache.thrift.protocol.TField SP_STR_FIELD_DESC = new org.apache.thrift.protocol.TField("spStr", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField FD_SUM_FIELD_DESC = new org.apache.thrift.protocol.TField("fdSum", org.apache.thrift.protocol.TType.I32, (short)2);
    private static final org.apache.thrift.protocol.TField WHERE_STR_FIELD_DESC = new org.apache.thrift.protocol.TField("whereStr", org.apache.thrift.protocol.TType.STRING, (short)3);
    private static final org.apache.thrift.protocol.TField SRC_DIR_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("srcDirName", org.apache.thrift.protocol.TType.STRING, (short)4);
    private static final org.apache.thrift.protocol.TField DST_DIR_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("dstDirName", org.apache.thrift.protocol.TType.STRING, (short)5);
    private static final org.apache.thrift.protocol.TField HOST_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("hostIp", org.apache.thrift.protocol.TType.STRING, (short)6);
    private static final org.apache.thrift.protocol.TField HOST_PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("hostPort", org.apache.thrift.protocol.TType.STRING, (short)7);
    private static final org.apache.thrift.protocol.TField HOST_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("hostName", org.apache.thrift.protocol.TType.STRING, (short)8);
    private static final org.apache.thrift.protocol.TField HOST_PASSWORD_FIELD_DESC = new org.apache.thrift.protocol.TField("hostPassword", org.apache.thrift.protocol.TType.STRING, (short)9);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new selectRec_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new selectRec_argsTupleSchemeFactory();

    public java.lang.String spStr; // required
    public int fdSum; // required
    public java.lang.String whereStr; // required
    public java.lang.String srcDirName; // required
    public java.lang.String dstDirName; // required
    public java.lang.String hostIp; // required
    public java.lang.String hostPort; // required
    public java.lang.String hostName; // required
    public java.lang.String hostPassword; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SP_STR((short)1, "spStr"),
      FD_SUM((short)2, "fdSum"),
      WHERE_STR((short)3, "whereStr"),
      SRC_DIR_NAME((short)4, "srcDirName"),
      DST_DIR_NAME((short)5, "dstDirName"),
      HOST_IP((short)6, "hostIp"),
      HOST_PORT((short)7, "hostPort"),
      HOST_NAME((short)8, "hostName"),
      HOST_PASSWORD((short)9, "hostPassword");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // SP_STR
            return SP_STR;
          case 2: // FD_SUM
            return FD_SUM;
          case 3: // WHERE_STR
            return WHERE_STR;
          case 4: // SRC_DIR_NAME
            return SRC_DIR_NAME;
          case 5: // DST_DIR_NAME
            return DST_DIR_NAME;
          case 6: // HOST_IP
            return HOST_IP;
          case 7: // HOST_PORT
            return HOST_PORT;
          case 8: // HOST_NAME
            return HOST_NAME;
          case 9: // HOST_PASSWORD
            return HOST_PASSWORD;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __FDSUM_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SP_STR, new org.apache.thrift.meta_data.FieldMetaData("spStr", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.FD_SUM, new org.apache.thrift.meta_data.FieldMetaData("fdSum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
      tmpMap.put(_Fields.WHERE_STR, new org.apache.thrift.meta_data.FieldMetaData("whereStr", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.SRC_DIR_NAME, new org.apache.thrift.meta_data.FieldMetaData("srcDirName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.DST_DIR_NAME, new org.apache.thrift.meta_data.FieldMetaData("dstDirName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.HOST_IP, new org.apache.thrift.meta_data.FieldMetaData("hostIp", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.HOST_PORT, new org.apache.thrift.meta_data.FieldMetaData("hostPort", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.HOST_NAME, new org.apache.thrift.meta_data.FieldMetaData("hostName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.HOST_PASSWORD, new org.apache.thrift.meta_data.FieldMetaData("hostPassword", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(selectRec_args.class, metaDataMap);
    }

    public selectRec_args() {
    }

    public selectRec_args(
      java.lang.String spStr,
      int fdSum,
      java.lang.String whereStr,
      java.lang.String srcDirName,
      java.lang.String dstDirName,
      java.lang.String hostIp,
      java.lang.String hostPort,
      java.lang.String hostName,
      java.lang.String hostPassword)
    {
      this();
      this.spStr = spStr;
      this.fdSum = fdSum;
      setFdSumIsSet(true);
      this.whereStr = whereStr;
      this.srcDirName = srcDirName;
      this.dstDirName = dstDirName;
      this.hostIp = hostIp;
      this.hostPort = hostPort;
      this.hostName = hostName;
      this.hostPassword = hostPassword;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public selectRec_args(selectRec_args other) {
      __isset_bitfield = other.__isset_bitfield;
      if (other.isSetSpStr()) {
        this.spStr = other.spStr;
      }
      this.fdSum = other.fdSum;
      if (other.isSetWhereStr()) {
        this.whereStr = other.whereStr;
      }
      if (other.isSetSrcDirName()) {
        this.srcDirName = other.srcDirName;
      }
      if (other.isSetDstDirName()) {
        this.dstDirName = other.dstDirName;
      }
      if (other.isSetHostIp()) {
        this.hostIp = other.hostIp;
      }
      if (other.isSetHostPort()) {
        this.hostPort = other.hostPort;
      }
      if (other.isSetHostName()) {
        this.hostName = other.hostName;
      }
      if (other.isSetHostPassword()) {
        this.hostPassword = other.hostPassword;
      }
    }

    public selectRec_args deepCopy() {
      return new selectRec_args(this);
    }

    
    public void clear() {
      this.spStr = null;
      setFdSumIsSet(false);
      this.fdSum = 0;
      this.whereStr = null;
      this.srcDirName = null;
      this.dstDirName = null;
      this.hostIp = null;
      this.hostPort = null;
      this.hostName = null;
      this.hostPassword = null;
    }

    public java.lang.String getSpStr() {
      return this.spStr;
    }

    public selectRec_args setSpStr(java.lang.String spStr) {
      this.spStr = spStr;
      return this;
    }

    public void unsetSpStr() {
      this.spStr = null;
    }

    /** Returns true if field spStr is set (has been assigned a value) and false otherwise */
    public boolean isSetSpStr() {
      return this.spStr != null;
    }

    public void setSpStrIsSet(boolean value) {
      if (!value) {
        this.spStr = null;
      }
    }

    public int getFdSum() {
      return this.fdSum;
    }

    public selectRec_args setFdSum(int fdSum) {
      this.fdSum = fdSum;
      setFdSumIsSet(true);
      return this;
    }

    public void unsetFdSum() {
      __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FDSUM_ISSET_ID);
    }

    /** Returns true if field fdSum is set (has been assigned a value) and false otherwise */
    public boolean isSetFdSum() {
      return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FDSUM_ISSET_ID);
    }

    public void setFdSumIsSet(boolean value) {
      __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FDSUM_ISSET_ID, value);
    }

    public java.lang.String getWhereStr() {
      return this.whereStr;
    }

    public selectRec_args setWhereStr(java.lang.String whereStr) {
      this.whereStr = whereStr;
      return this;
    }

    public void unsetWhereStr() {
      this.whereStr = null;
    }

    /** Returns true if field whereStr is set (has been assigned a value) and false otherwise */
    public boolean isSetWhereStr() {
      return this.whereStr != null;
    }

    public void setWhereStrIsSet(boolean value) {
      if (!value) {
        this.whereStr = null;
      }
    }

    public java.lang.String getSrcDirName() {
      return this.srcDirName;
    }

    public selectRec_args setSrcDirName(java.lang.String srcDirName) {
      this.srcDirName = srcDirName;
      return this;
    }

    public void unsetSrcDirName() {
      this.srcDirName = null;
    }

    /** Returns true if field srcDirName is set (has been assigned a value) and false otherwise */
    public boolean isSetSrcDirName() {
      return this.srcDirName != null;
    }

    public void setSrcDirNameIsSet(boolean value) {
      if (!value) {
        this.srcDirName = null;
      }
    }

    public java.lang.String getDstDirName() {
      return this.dstDirName;
    }

    public selectRec_args setDstDirName(java.lang.String dstDirName) {
      this.dstDirName = dstDirName;
      return this;
    }

    public void unsetDstDirName() {
      this.dstDirName = null;
    }

    /** Returns true if field dstDirName is set (has been assigned a value) and false otherwise */
    public boolean isSetDstDirName() {
      return this.dstDirName != null;
    }

    public void setDstDirNameIsSet(boolean value) {
      if (!value) {
        this.dstDirName = null;
      }
    }

    public java.lang.String getHostIp() {
      return this.hostIp;
    }

    public selectRec_args setHostIp(java.lang.String hostIp) {
      this.hostIp = hostIp;
      return this;
    }

    public void unsetHostIp() {
      this.hostIp = null;
    }

    /** Returns true if field hostIp is set (has been assigned a value) and false otherwise */
    public boolean isSetHostIp() {
      return this.hostIp != null;
    }

    public void setHostIpIsSet(boolean value) {
      if (!value) {
        this.hostIp = null;
      }
    }

    public java.lang.String getHostPort() {
      return this.hostPort;
    }

    public selectRec_args setHostPort(java.lang.String hostPort) {
      this.hostPort = hostPort;
      return this;
    }

    public void unsetHostPort() {
      this.hostPort = null;
    }

    /** Returns true if field hostPort is set (has been assigned a value) and false otherwise */
    public boolean isSetHostPort() {
      return this.hostPort != null;
    }

    public void setHostPortIsSet(boolean value) {
      if (!value) {
        this.hostPort = null;
      }
    }

    public java.lang.String getHostName() {
      return this.hostName;
    }

    public selectRec_args setHostName(java.lang.String hostName) {
      this.hostName = hostName;
      return this;
    }

    public void unsetHostName() {
      this.hostName = null;
    }

    /** Returns true if field hostName is set (has been assigned a value) and false otherwise */
    public boolean isSetHostName() {
      return this.hostName != null;
    }

    public void setHostNameIsSet(boolean value) {
      if (!value) {
        this.hostName = null;
      }
    }

    public java.lang.String getHostPassword() {
      return this.hostPassword;
    }

    public selectRec_args setHostPassword(java.lang.String hostPassword) {
      this.hostPassword = hostPassword;
      return this;
    }

    public void unsetHostPassword() {
      this.hostPassword = null;
    }

    /** Returns true if field hostPassword is set (has been assigned a value) and false otherwise */
    public boolean isSetHostPassword() {
      return this.hostPassword != null;
    }

    public void setHostPasswordIsSet(boolean value) {
      if (!value) {
        this.hostPassword = null;
      }
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
      switch (field) {
      case SP_STR:
        if (value == null) {
          unsetSpStr();
        } else {
          setSpStr((java.lang.String)value);
        }
        break;

      case FD_SUM:
        if (value == null) {
          unsetFdSum();
        } else {
          setFdSum((java.lang.Integer)value);
        }
        break;

      case WHERE_STR:
        if (value == null) {
          unsetWhereStr();
        } else {
          setWhereStr((java.lang.String)value);
        }
        break;

      case SRC_DIR_NAME:
        if (value == null) {
          unsetSrcDirName();
        } else {
          setSrcDirName((java.lang.String)value);
        }
        break;

      case DST_DIR_NAME:
        if (value == null) {
          unsetDstDirName();
        } else {
          setDstDirName((java.lang.String)value);
        }
        break;

      case HOST_IP:
        if (value == null) {
          unsetHostIp();
        } else {
          setHostIp((java.lang.String)value);
        }
        break;

      case HOST_PORT:
        if (value == null) {
          unsetHostPort();
        } else {
          setHostPort((java.lang.String)value);
        }
        break;

      case HOST_NAME:
        if (value == null) {
          unsetHostName();
        } else {
          setHostName((java.lang.String)value);
        }
        break;

      case HOST_PASSWORD:
        if (value == null) {
          unsetHostPassword();
        } else {
          setHostPassword((java.lang.String)value);
        }
        break;

      }
    }

    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SP_STR:
        return getSpStr();

      case FD_SUM:
        return getFdSum();

      case WHERE_STR:
        return getWhereStr();

      case SRC_DIR_NAME:
        return getSrcDirName();

      case DST_DIR_NAME:
        return getDstDirName();

      case HOST_IP:
        return getHostIp();

      case HOST_PORT:
        return getHostPort();

      case HOST_NAME:
        return getHostName();

      case HOST_PASSWORD:
        return getHostPassword();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SP_STR:
        return isSetSpStr();
      case FD_SUM:
        return isSetFdSum();
      case WHERE_STR:
        return isSetWhereStr();
      case SRC_DIR_NAME:
        return isSetSrcDirName();
      case DST_DIR_NAME:
        return isSetDstDirName();
      case HOST_IP:
        return isSetHostIp();
      case HOST_PORT:
        return isSetHostPort();
      case HOST_NAME:
        return isSetHostName();
      case HOST_PASSWORD:
        return isSetHostPassword();
      }
      throw new java.lang.IllegalStateException();
    }

    
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof selectRec_args)
        return this.equals((selectRec_args)that);
      return false;
    }

    public boolean equals(selectRec_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_spStr = true && this.isSetSpStr();
      boolean that_present_spStr = true && that.isSetSpStr();
      if (this_present_spStr || that_present_spStr) {
        if (!(this_present_spStr && that_present_spStr))
          return false;
        if (!this.spStr.equals(that.spStr))
          return false;
      }

      boolean this_present_fdSum = true;
      boolean that_present_fdSum = true;
      if (this_present_fdSum || that_present_fdSum) {
        if (!(this_present_fdSum && that_present_fdSum))
          return false;
        if (this.fdSum != that.fdSum)
          return false;
      }

      boolean this_present_whereStr = true && this.isSetWhereStr();
      boolean that_present_whereStr = true && that.isSetWhereStr();
      if (this_present_whereStr || that_present_whereStr) {
        if (!(this_present_whereStr && that_present_whereStr))
          return false;
        if (!this.whereStr.equals(that.whereStr))
          return false;
      }

      boolean this_present_srcDirName = true && this.isSetSrcDirName();
      boolean that_present_srcDirName = true && that.isSetSrcDirName();
      if (this_present_srcDirName || that_present_srcDirName) {
        if (!(this_present_srcDirName && that_present_srcDirName))
          return false;
        if (!this.srcDirName.equals(that.srcDirName))
          return false;
      }

      boolean this_present_dstDirName = true && this.isSetDstDirName();
      boolean that_present_dstDirName = true && that.isSetDstDirName();
      if (this_present_dstDirName || that_present_dstDirName) {
        if (!(this_present_dstDirName && that_present_dstDirName))
          return false;
        if (!this.dstDirName.equals(that.dstDirName))
          return false;
      }

      boolean this_present_hostIp = true && this.isSetHostIp();
      boolean that_present_hostIp = true && that.isSetHostIp();
      if (this_present_hostIp || that_present_hostIp) {
        if (!(this_present_hostIp && that_present_hostIp))
          return false;
        if (!this.hostIp.equals(that.hostIp))
          return false;
      }

      boolean this_present_hostPort = true && this.isSetHostPort();
      boolean that_present_hostPort = true && that.isSetHostPort();
      if (this_present_hostPort || that_present_hostPort) {
        if (!(this_present_hostPort && that_present_hostPort))
          return false;
        if (!this.hostPort.equals(that.hostPort))
          return false;
      }

      boolean this_present_hostName = true && this.isSetHostName();
      boolean that_present_hostName = true && that.isSetHostName();
      if (this_present_hostName || that_present_hostName) {
        if (!(this_present_hostName && that_present_hostName))
          return false;
        if (!this.hostName.equals(that.hostName))
          return false;
      }

      boolean this_present_hostPassword = true && this.isSetHostPassword();
      boolean that_present_hostPassword = true && that.isSetHostPassword();
      if (this_present_hostPassword || that_present_hostPassword) {
        if (!(this_present_hostPassword && that_present_hostPassword))
          return false;
        if (!this.hostPassword.equals(that.hostPassword))
          return false;
      }

      return true;
    }

    
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSpStr()) ? 131071 : 524287);
      if (isSetSpStr())
        hashCode = hashCode * 8191 + spStr.hashCode();

      hashCode = hashCode * 8191 + fdSum;

      hashCode = hashCode * 8191 + ((isSetWhereStr()) ? 131071 : 524287);
      if (isSetWhereStr())
        hashCode = hashCode * 8191 + whereStr.hashCode();

      hashCode = hashCode * 8191 + ((isSetSrcDirName()) ? 131071 : 524287);
      if (isSetSrcDirName())
        hashCode = hashCode * 8191 + srcDirName.hashCode();

      hashCode = hashCode * 8191 + ((isSetDstDirName()) ? 131071 : 524287);
      if (isSetDstDirName())
        hashCode = hashCode * 8191 + dstDirName.hashCode();

      hashCode = hashCode * 8191 + ((isSetHostIp()) ? 131071 : 524287);
      if (isSetHostIp())
        hashCode = hashCode * 8191 + hostIp.hashCode();

      hashCode = hashCode * 8191 + ((isSetHostPort()) ? 131071 : 524287);
      if (isSetHostPort())
        hashCode = hashCode * 8191 + hostPort.hashCode();

      hashCode = hashCode * 8191 + ((isSetHostName()) ? 131071 : 524287);
      if (isSetHostName())
        hashCode = hashCode * 8191 + hostName.hashCode();

      hashCode = hashCode * 8191 + ((isSetHostPassword()) ? 131071 : 524287);
      if (isSetHostPassword())
        hashCode = hashCode * 8191 + hostPassword.hashCode();

      return hashCode;
    }

    
    public int compareTo(selectRec_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetSpStr()).compareTo(other.isSetSpStr());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSpStr()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.spStr, other.spStr);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetFdSum()).compareTo(other.isSetFdSum());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetFdSum()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fdSum, other.fdSum);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetWhereStr()).compareTo(other.isSetWhereStr());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetWhereStr()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.whereStr, other.whereStr);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetSrcDirName()).compareTo(other.isSetSrcDirName());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSrcDirName()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.srcDirName, other.srcDirName);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetDstDirName()).compareTo(other.isSetDstDirName());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetDstDirName()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dstDirName, other.dstDirName);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetHostIp()).compareTo(other.isSetHostIp());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetHostIp()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hostIp, other.hostIp);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetHostPort()).compareTo(other.isSetHostPort());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetHostPort()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hostPort, other.hostPort);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetHostName()).compareTo(other.isSetHostName());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetHostName()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hostName, other.hostName);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetHostPassword()).compareTo(other.isSetHostPassword());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetHostPassword()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hostPassword, other.hostPassword);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("selectRec_args(");
      boolean first = true;

      sb.append("spStr:");
      if (this.spStr == null) {
        sb.append("null");
      } else {
        sb.append(this.spStr);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("fdSum:");
      sb.append(this.fdSum);
      first = false;
      if (!first) sb.append(", ");
      sb.append("whereStr:");
      if (this.whereStr == null) {
        sb.append("null");
      } else {
        sb.append(this.whereStr);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("srcDirName:");
      if (this.srcDirName == null) {
        sb.append("null");
      } else {
        sb.append(this.srcDirName);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("dstDirName:");
      if (this.dstDirName == null) {
        sb.append("null");
      } else {
        sb.append(this.dstDirName);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("hostIp:");
      if (this.hostIp == null) {
        sb.append("null");
      } else {
        sb.append(this.hostIp);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("hostPort:");
      if (this.hostPort == null) {
        sb.append("null");
      } else {
        sb.append(this.hostPort);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("hostName:");
      if (this.hostName == null) {
        sb.append("null");
      } else {
        sb.append(this.hostName);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("hostPassword:");
      if (this.hostPassword == null) {
        sb.append("null");
      } else {
        sb.append(this.hostPassword);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class selectRec_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public selectRec_argsStandardScheme getScheme() {
        return new selectRec_argsStandardScheme();
      }
    }

    private static class selectRec_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<selectRec_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, selectRec_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // SP_STR
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.spStr = iprot.readString();
                struct.setSpStrIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // FD_SUM
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.fdSum = iprot.readI32();
                struct.setFdSumIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // WHERE_STR
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.whereStr = iprot.readString();
                struct.setWhereStrIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 4: // SRC_DIR_NAME
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.srcDirName = iprot.readString();
                struct.setSrcDirNameIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 5: // DST_DIR_NAME
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.dstDirName = iprot.readString();
                struct.setDstDirNameIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 6: // HOST_IP
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.hostIp = iprot.readString();
                struct.setHostIpIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 7: // HOST_PORT
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.hostPort = iprot.readString();
                struct.setHostPortIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 8: // HOST_NAME
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.hostName = iprot.readString();
                struct.setHostNameIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 9: // HOST_PASSWORD
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.hostPassword = iprot.readString();
                struct.setHostPasswordIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, selectRec_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.spStr != null) {
          oprot.writeFieldBegin(SP_STR_FIELD_DESC);
          oprot.writeString(struct.spStr);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldBegin(FD_SUM_FIELD_DESC);
        oprot.writeI32(struct.fdSum);
        oprot.writeFieldEnd();
        if (struct.whereStr != null) {
          oprot.writeFieldBegin(WHERE_STR_FIELD_DESC);
          oprot.writeString(struct.whereStr);
          oprot.writeFieldEnd();
        }
        if (struct.srcDirName != null) {
          oprot.writeFieldBegin(SRC_DIR_NAME_FIELD_DESC);
          oprot.writeString(struct.srcDirName);
          oprot.writeFieldEnd();
        }
        if (struct.dstDirName != null) {
          oprot.writeFieldBegin(DST_DIR_NAME_FIELD_DESC);
          oprot.writeString(struct.dstDirName);
          oprot.writeFieldEnd();
        }
        if (struct.hostIp != null) {
          oprot.writeFieldBegin(HOST_IP_FIELD_DESC);
          oprot.writeString(struct.hostIp);
          oprot.writeFieldEnd();
        }
        if (struct.hostPort != null) {
          oprot.writeFieldBegin(HOST_PORT_FIELD_DESC);
          oprot.writeString(struct.hostPort);
          oprot.writeFieldEnd();
        }
        if (struct.hostName != null) {
          oprot.writeFieldBegin(HOST_NAME_FIELD_DESC);
          oprot.writeString(struct.hostName);
          oprot.writeFieldEnd();
        }
        if (struct.hostPassword != null) {
          oprot.writeFieldBegin(HOST_PASSWORD_FIELD_DESC);
          oprot.writeString(struct.hostPassword);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class selectRec_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public selectRec_argsTupleScheme getScheme() {
        return new selectRec_argsTupleScheme();
      }
    }

    private static class selectRec_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<selectRec_args> {

      
      public void write(org.apache.thrift.protocol.TProtocol prot, selectRec_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSpStr()) {
          optionals.set(0);
        }
        if (struct.isSetFdSum()) {
          optionals.set(1);
        }
        if (struct.isSetWhereStr()) {
          optionals.set(2);
        }
        if (struct.isSetSrcDirName()) {
          optionals.set(3);
        }
        if (struct.isSetDstDirName()) {
          optionals.set(4);
        }
        if (struct.isSetHostIp()) {
          optionals.set(5);
        }
        if (struct.isSetHostPort()) {
          optionals.set(6);
        }
        if (struct.isSetHostName()) {
          optionals.set(7);
        }
        if (struct.isSetHostPassword()) {
          optionals.set(8);
        }
        oprot.writeBitSet(optionals, 9);
        if (struct.isSetSpStr()) {
          oprot.writeString(struct.spStr);
        }
        if (struct.isSetFdSum()) {
          oprot.writeI32(struct.fdSum);
        }
        if (struct.isSetWhereStr()) {
          oprot.writeString(struct.whereStr);
        }
        if (struct.isSetSrcDirName()) {
          oprot.writeString(struct.srcDirName);
        }
        if (struct.isSetDstDirName()) {
          oprot.writeString(struct.dstDirName);
        }
        if (struct.isSetHostIp()) {
          oprot.writeString(struct.hostIp);
        }
        if (struct.isSetHostPort()) {
          oprot.writeString(struct.hostPort);
        }
        if (struct.isSetHostName()) {
          oprot.writeString(struct.hostName);
        }
        if (struct.isSetHostPassword()) {
          oprot.writeString(struct.hostPassword);
        }
      }

      
      public void read(org.apache.thrift.protocol.TProtocol prot, selectRec_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(9);
        if (incoming.get(0)) {
          struct.spStr = iprot.readString();
          struct.setSpStrIsSet(true);
        }
        if (incoming.get(1)) {
          struct.fdSum = iprot.readI32();
          struct.setFdSumIsSet(true);
        }
        if (incoming.get(2)) {
          struct.whereStr = iprot.readString();
          struct.setWhereStrIsSet(true);
        }
        if (incoming.get(3)) {
          struct.srcDirName = iprot.readString();
          struct.setSrcDirNameIsSet(true);
        }
        if (incoming.get(4)) {
          struct.dstDirName = iprot.readString();
          struct.setDstDirNameIsSet(true);
        }
        if (incoming.get(5)) {
          struct.hostIp = iprot.readString();
          struct.setHostIpIsSet(true);
        }
        if (incoming.get(6)) {
          struct.hostPort = iprot.readString();
          struct.setHostPortIsSet(true);
        }
        if (incoming.get(7)) {
          struct.hostName = iprot.readString();
          struct.setHostNameIsSet(true);
        }
        if (incoming.get(8)) {
          struct.hostPassword = iprot.readString();
          struct.setHostPasswordIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class selectRec_result implements org.apache.thrift.TBase<selectRec_result, selectRec_result._Fields>, java.io.Serializable, Cloneable, Comparable<selectRec_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("selectRec_result");


    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new selectRec_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new selectRec_resultTupleSchemeFactory();


    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
;

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(selectRec_result.class, metaDataMap);
    }

    public selectRec_result() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public selectRec_result(selectRec_result other) {
    }

    public selectRec_result deepCopy() {
      return new selectRec_result(this);
    }

    
    public void clear() {
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
      switch (field) {
      }
    }

    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      }
      throw new java.lang.IllegalStateException();
    }

    
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof selectRec_result)
        return this.equals((selectRec_result)that);
      return false;
    }

    public boolean equals(selectRec_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      return true;
    }

    
    public int hashCode() {
      int hashCode = 1;

      return hashCode;
    }

    
    public int compareTo(selectRec_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("selectRec_result(");
      boolean first = true;

      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class selectRec_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public selectRec_resultStandardScheme getScheme() {
        return new selectRec_resultStandardScheme();
      }
    }

    private static class selectRec_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<selectRec_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, selectRec_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, selectRec_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class selectRec_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public selectRec_resultTupleScheme getScheme() {
        return new selectRec_resultTupleScheme();
      }
    }

    private static class selectRec_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<selectRec_result> {

      
      public void write(org.apache.thrift.protocol.TProtocol prot, selectRec_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      }

      
      public void read(org.apache.thrift.protocol.TProtocol prot, selectRec_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
